// Code generated by "./generator ./com.deepin.daemon.imageeffect"; DO NOT EDIT.

package imageeffect

import (
	"fmt"

	"github.com/godbus/dbus"
	"github.com/stretchr/testify/mock"
)

type MockImageEffect struct {
	mockInterfaceImageEffect // interface com.deepin.daemon.ImageEffect
}

type mockInterfaceImageEffect struct {
	mock.Mock
}

// method Delete

func (v *mockInterfaceImageEffect) GoDelete(flags dbus.Flags, ch chan *dbus.Call, effect string, filename string) *dbus.Call {
	mockArgs := v.Called(flags, ch, effect, filename)

	ret, ok := mockArgs.Get(0).(*dbus.Call)
	if !ok {
		panic(fmt.Sprintf("assert: arguments: 0 failed because object wasn't correct type: %v", mockArgs.Get(0)))
	}

	return ret
}

func (v *mockInterfaceImageEffect) Delete(flags dbus.Flags, effect string, filename string) error {
	mockArgs := v.Called(flags, effect, filename)

	return mockArgs.Error(0)
}

// method Get

func (v *mockInterfaceImageEffect) GoGet(flags dbus.Flags, ch chan *dbus.Call, effect string, filename string) *dbus.Call {
	mockArgs := v.Called(flags, ch, effect, filename)

	ret, ok := mockArgs.Get(0).(*dbus.Call)
	if !ok {
		panic(fmt.Sprintf("assert: arguments: 0 failed because object wasn't correct type: %v", mockArgs.Get(0)))
	}

	return ret
}

func (v *mockInterfaceImageEffect) Get(flags dbus.Flags, effect string, filename string) (string, error) {
	mockArgs := v.Called(flags, effect, filename)

	ret0, ok := mockArgs.Get(0).(string)
	if !ok {
		panic(fmt.Sprintf("assert: arguments: %d failed because object wasn't correct type: %v", 0, mockArgs.Get(0)))
	}

	return ret0, mockArgs.Error(1)
}
