// Code generated by "./generator ./com.deepin.dde.osd"; DO NOT EDIT.

package osd

import (
	"fmt"

	"github.com/godbus/dbus"
	"github.com/stretchr/testify/mock"
	"github.com/linuxdeepin/go-lib/dbusutil/proxy"
)

type MockOSD struct {
	MockInterfaceOsd // interface com.deepin.dde.osd
	proxy.MockObject
}

type MockInterfaceOsd struct {
	mock.Mock
}

// method ShowOSD

func (v *MockInterfaceOsd) GoShowOSD(flags dbus.Flags, ch chan *dbus.Call, osd string) *dbus.Call {
	mockArgs := v.Called(flags, ch, osd)

	ret, ok := mockArgs.Get(0).(*dbus.Call)
	if !ok {
		panic(fmt.Sprintf("assert: arguments: 0 failed because object wasn't correct type: %v", mockArgs.Get(0)))
	}

	return ret
}

func (v *MockInterfaceOsd) ShowOSD(flags dbus.Flags, osd string) error {
	mockArgs := v.Called(flags, osd)

	return mockArgs.Error(0)
}
