// Code generated by "./generator ./com.deepin.system.systeminfo"; DO NOT EDIT.

package systeminfo

import (
	"fmt"

	"github.com/stretchr/testify/mock"
	"pkg.deepin.io/lib/dbusutil/proxy"
)

type MockSystemInfo struct {
	MockInterfaceSystemInfo // interface com.deepin.system.SystemInfo
	proxy.MockObject
}

type MockInterfaceSystemInfo struct {
	mock.Mock
}

// property MemorySizeHuman s

func (v *MockInterfaceSystemInfo) MemorySizeHuman() proxy.PropString {
	mockArgs := v.Called()

	ret0, ok := mockArgs.Get(0).(*proxy.MockPropString)
	if !ok {
		panic(fmt.Sprintf("assert: arguments: %d failed because object wasn't correct type: %v", 0, mockArgs.Get(0)))
	}

	return ret0
}

// property MemorySize t

func (v *MockInterfaceSystemInfo) MemorySize() proxy.PropUint64 {
	mockArgs := v.Called()

	ret0, ok := mockArgs.Get(0).(*proxy.MockPropUint64)
	if !ok {
		panic(fmt.Sprintf("assert: arguments: %d failed because object wasn't correct type: %v", 0, mockArgs.Get(0)))
	}

	return ret0
}

// property CurrentSpeed t

func (v *MockInterfaceSystemInfo) CurrentSpeed() proxy.PropUint64 {
	mockArgs := v.Called()

	ret0, ok := mockArgs.Get(0).(*proxy.MockPropUint64)
	if !ok {
		panic(fmt.Sprintf("assert: arguments: %d failed because object wasn't correct type: %v", 0, mockArgs.Get(0)))
	}

	return ret0
}
