// Code generated by "./generator com.deepin.daemon.bluetooth/"; DO NOT EDIT.

package bluetooth

import "fmt"
import "github.com/godbus/dbus"
import "github.com/stretchr/testify/mock"

import "pkg.deepin.io/lib/dbusutil/proxy"

type MockBluetooth struct {
	MockInterfaceBluetooth // interface com.deepin.daemon.Bluetooth
	proxy.MockObject
}

type MockInterfaceBluetooth struct {
	mock.Mock
}

// method DisconnectAllDevices

func (v *MockInterfaceBluetooth) GoDisconnectAllDevices(flags dbus.Flags, ch chan *dbus.Call) *dbus.Call {
	mockArgs := v.Called(flags, ch)

	ret, ok := mockArgs.Get(0).(*dbus.Call)
	if !ok {
		panic(fmt.Sprintf("assert: arguments: 0 failed because object wasn't correct type: %v", mockArgs.Get(0)))
	}

	return ret
}

func (v *MockInterfaceBluetooth) DisconnectAllDevices(flags dbus.Flags) error {
	mockArgs := v.Called(flags)

	return mockArgs.Error(0)
}
